# Generated by Django 5.2 on 2025-04-30 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="deadlain",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="submission",
            name="submitted_at",
            field=models.DateTimeField(null=True),
        ),
    ]
