# Generated by Django 5.2 on 2025-04-30 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_submission_deadlain_alter_submission_submitted_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assignment",
            name="due_date",
        ),
        migrations.RemoveField(
            model_name="submission",
            name="deadlain",
        ),
        migrations.AddField(
            model_name="assignment",
            name="deadlain",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="submission",
            name="submitted_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
