# Generated by Django 5.2 on 2025-04-30 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_remove_assignment_due_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="submitted_at",
            field=models.DateTimeField(null=True),
        ),
    ]
