# Generated by Django 5.2 on 2025-04-30 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_alter_submission_submitted_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="file_assignment",
            field=models.FileField(
                blank=True, null=True, upload_to="file_assignments/"
            ),
        ),
    ]
